language: cpp
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - cmake
script: if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi && cmake . && make && ./all_tes
