language: cpp
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - cmake
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
script: 
  - cmake .
  - make 
  - ./all_tests
