#ifndef THUNDERBOTS_NAVIGATOR_WORLDGRAPHFACTORY_H
#define THUNDERBOTS_NAVIGATOR_WORLDGRAPHFACTORY_H

// TODO: Descriptive comment for this class
class WorldGraphFactory {
};

#endif //THUNDERBOTS_NAVIGATOR_WORLDGRAPHFACTORY_H
